### ISSUE TITLE
Error: Could not execute entrypoint stage 'server'

### ISSUE THREAD

**Issue by fieu** [QuiltServerTools/Ledger#167]
### Expected behavior

For Ledger to load properly

### Observed/actual behavior

Error when starting up server:
```
mc-smp    | [01:09:21] [main/INFO]: Initializing Ledger 1.2.4
mc-smp    | [01:09:23] [main/ERROR]: Failed to start the minecraft server
mc-smp    | java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'ledger'!
mc-smp    |     at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.4.jar:?]
mc-smp    |     at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.4.jar:?]
mc-smp    |     at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.4.jar:?]
mc-smp    |     at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.4.jar:?]
mc-smp    |     at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.4.jar:?]
mc-smp    |     at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
mc-smp    |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
mc-smp    |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
mc-smp    |     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
mc-smp    |     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
mc-smp    |     at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.4.jar:?]
mc-smp    |     at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
mc-smp    |     at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.4.jar:?]
mc-smp    |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
mc-smp    |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
mc-smp    |     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
mc-smp    |     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
mc-smp    |     at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:67) [fabric-loader-0.14.4.jar:?]
mc-smp    |     at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [fabric-server-mc.1.18.2-loader.0.14.4-launcher.0.10.2.jar:0.10.2]
mc-smp    | Caused by: java.lang.ExceptionInInitializerError
mc-smp    |     at com.github.quiltservertools.ledger.Ledger.onInitializeServer(Ledger.kt:69) ~[ledger-1.2.4.jar:?]
mc-smp    |     at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.4.jar:?]
mc-smp    |     ... 16 more
mc-smp    | Caused by: java.io.IOException: User limit of inotify watches reached
mc-smp    |     at sun.nio.fs.LinuxWatchService$Poller.implRegister(Unknown Source) ~[?:?]
mc-smp    |     at sun.nio.fs.AbstractPoller.processRequests(Unknown Source) ~[?:?]
mc-smp    |     at sun.nio.fs.LinuxWatchService$Poller.run(Unknown Source) ~[?:?]
mc-smp    |     at java.lang.Thread.run(Unknown Source) ~[?:?]
mc-smp    | 2022-05-08T01:09:23.991+0200        INFO    mc-server-runner        Done
```

### Steps/models to reproduce

1. Start server

### What operating system are you running

Linux

### Minecraft version

1.18.2

### Ledger version

1.2.4

### Logs

https://mclo.gs/N4plCJh

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by fieu** [comment]
Found out the error. Looked more into the `Caused by: java.io.IOException: User limit of inotify watches reached` as that seems to be a generic Java error rather than mod specific.

Turns out running `cat /proc/sys/fs/inotify/max_user_watches` spits out `8192`.

Running the following commands below fixes the error:
```sh
echo 16384 | sudo tee /proc/sys/fs/inotify/max_user_watches
echo fs.inotify.max_user_watches=16384 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
```

I'm leaving the issue open as I still view it as a bug, though I could be wrong.
