### ISSUE TITLE
Ledger conflicts with Simple Voice Chat due to Permissions api

### ISSUE THREAD

**Issue by skerit** [QuiltServerTools/Ledger#173]
### Expected behavior

When I load my server with simple voice chat (`voicechat-fabric-1.19-2.2.45.jar`) and a **configured** Ledger + Ledget-database (`ledger-1.2.5.jar`) I get this error when someone joins the server:

```
	[13:40:39] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
	at de.maxhenkel.voicechat.command.VoicechatCommands.lambda$register$2(VoicechatCommands.java:44) ~[voicechat-fabric-1.19-2.2.45.jar:?]
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:65) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.server.command.CommandManager.makeTreeForSource(CommandManager.java:320) ~[server-intermediary.jar:?]
	at net.minecraft.server.command.CommandManager.makeTreeForSource(CommandManager.java:343) ~[server-intermediary.jar:?]
	at net.minecraft.server.command.CommandManager.sendCommandTree(CommandManager.java:314) ~[server-intermediary.jar:?]
	at net.minecraft.server.PlayerManager.sendCommandTree(PlayerManager.java:641) ~[server-intermediary.jar:?]
	at net.minecraft.server.PlayerManager.sendCommandTree(PlayerManager.java:542) ~[server-intermediary.jar:?]
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager.java:203) ~[server-intermediary.jar:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.addToServer(ServerLoginNetworkHandler.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler.java:127) ~[server-intermediary.jar:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$zoo000$handlePlayerJoin(ServerLoginNetworkHandler.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler.java:77) ~[server-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection.java:242) ~[server-intermediary.jar:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:182) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:886) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zfb000$modifiedRunLoop(MinecraftServer.java:4380) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Failed to load service 'PermissionManager'
	at de.maxhenkel.voicechat.service.Service.lambda$get$0(Service.java:8) ~[voicechat-fabric-1.19-2.2.45.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at de.maxhenkel.voicechat.service.Service.get(Service.java:8) ~[voicechat-fabric-1.19-2.2.45.jar:?]
	at de.maxhenkel.voicechat.permission.PermissionManager.<clinit>(PermissionManager.java:11) ~[voicechat-fabric-1.19-2.2.45.jar:?]
	... 21 more
```

### Observed/actual behavior

This error

### Steps/models to reproduce

Add both Simple voice chat & ledger to a 1.19 server

### What operating system are you running

Linux

### Minecraft version

1.19

### Ledger version

1.2.5

### Logs

https://mclo.gs/uzJOJDE

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by PotatoPresident** [comment]
They have support for permissions, something is going very wrong on their end. Make an issue on their page.
