### ISSUE TITLE
[Bug] Ledger causes minecraft to crash when the server stops

### ISSUE THREAD

**Issue by Eatham532** [QuiltServerTools/Ledger#176]
### Expected behavior

Server to stop

### Observed/actual behavior

Got the exception:

```shell
[16:08:56] [Server thread/ERROR]: Exception stopping the server
java.lang.NoSuchMethodError: 'long kotlin.time.Duration$Companion.minutes-UwyO8pc(long)'
at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
at com.github.quiltservertools.ledger.Ledger$serverStopped$1.invokeSuspend(Ledger.kt:100) ~[ledger-1.2.5.jar:?]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[minecord-api-1.0.0-beta.2-334e7ed5a4687c1b.jar:?]
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.3-972f7b22afdb69c1.jar:?]
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.3-972f7b22afdb69c1.jar:?]
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.3-972f7b22afdb69c1.jar:?]
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.3-972f7b22afdb69c1.jar:?]
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.3-972f7b22afdb69c1.jar:?]
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.3-972f7b22afdb69c1.jar:?]
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.3-972f7b22afdb69c1.jar:?]
at com.github.quiltservertools.ledger.Ledger.serverStopped(Ledger.kt:99) ~[ledger-1.2.5.jar:?]
at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$6(ServerLifecycleEvents.java:76) ~[fabric-lifecycle-events-v1-2.1.0+33fbc738a9-9d72f0d3e8ad527a.jar:?]
at net.minecraft.server.MinecraftServer.handler$cfm000$afterShutdownServer(MinecraftServer:7806) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.shutdown(MinecraftServer:610) ~[server-intermediary.jar:?]
at net.minecraft.server.dedicated.MinecraftDedicatedServer.shutdown(MinecraftDedicatedServer:547) ~[?:?]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps/models to reproduce

1. Add the mod to your server
2. Stop the server
3. Observe the bug

### What operating system are you running

Linux

### Minecraft version

1.19

### Ledger version

1.2.5

### Logs

Look in Observed behaviour

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by PotatoPresident** [comment]
Downgrade fabric language kotlin to 1.7-kotlin1.6

**Comment by Hedwig7s** [comment]
> Downgrade fabric language kotlin to 1.7-kotlin1.6

Still occurs in the latest 1.20.1 version
