### ISSUE TITLE
Ledger incompatibility causes java to crash

### ISSUE THREAD

**Issue by Eatham532** [QuiltServerTools/Ledger#179]
### Expected behavior

The server to stop as normal.

### Observed/actual behavior

When combining Ledger with the mod Minecord, java crashes. I created a [bug report on minecord](https://github.com/axieum/minecord/issues/44) and I was told that this is a ledger issue. There is no crash log.

Error. 

```shell
java.lang.NoSuchMethodError: 'long kotlin.time.Duration$Companion.minutes-UwyO8pc(long)'
at com.github.quiltservertools.ledger.Ledger$serverStopped$1.invokeSuspend(Ledger.kt:100) ~[ledger-1.2.5.jar:?]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[minecord-api-1.0.0-beta.2-37094233aadedb4d.jar:?]
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at com.github.quiltservertools.ledger.Ledger.serverStopped(Ledger.kt:99) ~[ledger-1.2.5.jar:?]
at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$6(ServerLifecycleEvents.java:76) ~[fabric-lifecycle-events-v1-2.1.0+33fbc738a9-c697e79f4c4115d8.jar:?]
at net.minecraft.server.MinecraftServer.handler$cjj000$afterShutdownServer(MinecraftServer.java:8306) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:610) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_3782(class_3176.java:547) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps/models to reproduce

1. Put the mods ledger and minecord your mods folder
2. Stop the server (I think saving and quitting your world will work as well)
3. Experience the bug

### What operating system are you running

Linux

### Minecraft version

1.19

### Ledger version

1.2.5

### Logs

n/a

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by PotatoPresident** [comment]
How would the logs not be applicable? 🤔 
Anyway, update fabric language kotlin.

**Comment by Eatham532** [comment]
Oh sorry about that. I meant that the logs were irrelevent. 🤦‍♂️ Sorry.
