### ISSUE TITLE
Ledger wont start on my server

### ISSUE THREAD

**Issue by Uniqeues** [QuiltServerTools/Ledger#209]
### Expected behavior

I shut down my fabric 1.19.4 server and installed Ledger 1.2.7 than I tried starting my server but nothing happened. As I uninstalled ledger my server started normally. I have no mods installed on server.

### Observed/actual behavior

Nothing my server won't start

### Steps/models to reproduce

Installed 1.19.4 Fabric
Turn on server and nothing happened
This is the version of fabric I have but in the log was written that I didint have fabric installed
![image](https://github.com/QuiltServerTools/Ledger/assets/101985113/791a892e-d566-436b-9f63-b6194f281cb3)

### What operating system are you running

Windows

### Minecraft version

1.19.4

### Ledger version

1.2.7

### Logs

[19:03:03] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.17 [19:03:03] [main/WARN]: Mod resolution failed [19:03:03] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE ledger 1.2.7 {depends fabric @ [>=0.75.3+1.19.4]}, ROOT_FORCELOAD_SINGLE ledger 1.2.7] [19:03:03] [main/INFO]: Reason: [HARD_DEP ledger 1.2.7 {depends fabric @ [>=0.75.3+1.19.4]}, HARD_DEP ledger 1.2.7 {depends fabric-language-kotlin @ [>=1.8.7+kotlin.1.7.22]}, HARD_DEP ledger-databases 1.1.1 {depends fabric @ [*]}, HARD_DEP ledger-databases 1.1.1 {depends fabric-language-kotlin @ [*]}] [19:03:03] [main/INFO]: Fix: add [add:fabric 0.75.3+1.19.4 ([[0.75.3+1.19.4,∞)]), add:fabric-language-kotlin 1.8.7+kotlin.1.7.22 ([[1.8.7+kotlin.1.7.22,∞)])], remove [], replace [] [19:03:04] [main/ERROR]: Incompatible mod set! net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: 	 - Install fabric, version 0.75.3+1.19.4 or later. 	 - Install fabric-language-kotlin, version 1.8.7+kotlin.1.7.22 or later. Unmet dependency listing: 	 - Mod 'Ledger' (ledger) 1.2.7 requires version 0.75.3+1.19.4 or later of fabric, which is missing! 	 - Mod 'Ledger' (ledger) 1.2.7 requires version 1.8.7+kotlin.1.7.22 or later of fabric-language-kotlin, which is missing! 	 - Mod 'Ledger Databases' (ledger-databases) 1.1.1 requires any version of fabric, which is missing! 	 - Mod 'Ledger Databases' (ledger-databases) 1.1.1 requires any version of fabric-language-kotlin, which is missing! 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.17.jar:?] 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.17.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.17.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.17.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.17.jar:?] 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.17.jar:?]

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by arnokeesman** [comment]
Error says fabric is missing, this means you need to install fabric-api.

**Comment by Uniqeues** [comment]
> 
I've installed fabric api but it says it need fabric loader 1.14.19 and I dont know how to install that. Do I put it in mods folder?

[18:03:03] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.17
[18:03:03] [main/WARN]: Mod resolution failed
[18:03:03] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE fabric-api 0.81.0+1.19.4 {depends fabricloader @ [>=0.14.19]}, ROOT_FORCELOAD_SINGLE fabric-api 0.81.0+1.19.4]
[18:03:03] [main/INFO]: Reason: [HARD_DEP fabric-api 0.81.0+1.19.4 {depends fabricloader @ [>=0.14.19]}, HARD_DEP ledger 1.2.7 {depends fabric-language-kotlin @ [>=1.8.7+kotlin.1.7.22]}, HARD_DEP ledger-databases 1.1.1 {depends fabric-language-kotlin @ [*]}]
[18:03:03] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-models-v0, fabric-client-tags-api-v1, fabric-rendering-v0, fabric-screen-api-v1, fabric-sound-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[18:03:03] [main/INFO]: Fix: add [add:fabric-language-kotlin 1.8.7+kotlin.1.7.22 ([[1.8.7+kotlin.1.7.22,∞)])], remove [], replace [[fabricloader 0.14.17] -> add:fabricloader 0.14.19 ([[0.14.19,∞)])]
[18:03:03] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-language-kotlin, version 1.8.7+kotlin.1.7.22 or later.
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.17 with version 0.14.19 or later.
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric-api) 0.81.0+1.19.4 requires version 0.14.19 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.17!
	 - Mod 'Ledger' (ledger) 1.2.7 requires version 1.8.7+kotlin.1.7.22 or later of fabric-language-kotlin, which is missing!
	 - Mod 'Ledger Databases' (ledger-databases) 1.1.1 requires any version of fabric-language-kotlin, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.17.jar:?]

**Comment by PotatoPresident** [comment]
Install a newer version of the fabric loader. You can rerun the fabric install or use [this](https://fabricmc.net/use/server/)

**Comment by Uniqeues** [comment]
I have only acces to these folders do I put it somewhere here? 
![image](https://github.com/QuiltServerTools/Ledger/assets/101985113/e1cea495-aa35-4d0b-bed6-ac323844ed21)
