### ISSUE TITLE
When shutting down the server, an error occurred while restoring the server files to 1 hour ago.

### ISSUE THREAD

**Issue by Natsusomekeishi** [QuiltServerTools/Ledger#287]
### Expected behavior

No error reported

### Observed/actual behavior

[DefaultDispatcher-worker-8/信息]: Registry insert complete
[14:48:43] [DefaultDispatcher-worker-8/信息]: Purging actions older than 15 days
[14:48:44] [DefaultDispatcher-worker-8/警告]: Transaction attempt #0 failed: org.sqlite.SQLiteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed). Statement(s): DELETE FROM actions WHERE actions."time" <= ?
org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:94) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:244) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:221) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:55) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.DeleteStatement$Companion.where(DeleteStatement.kt:47) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.deleteWhere(Queries.kt:112) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.deleteWhere$default(Queries.kt:111) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$autoPurge$2.invokeSuspend(DatabaseManager.kt:133) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$autoPurge$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$autoPurge$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2.invokeSuspend(DatabaseManager.kt:384) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:187) [ledger-1.3.4.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [org_jetbrains_kotlin_kotlin-stdlib-2.0.0-e823d47a24b16be4.jar:?]
        at kotlinx.coroutines.Dispatched任务.run(DispatchedTask.kt:104) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.任务Impl.run(Tasks.kt:99) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.execute任务(CoroutineScheduler.kt:811) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
Caused by: org.sqlite.SQLiteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
        at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.DB.execute(DB.java:988) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.DB.executeUpdate(DB.java:1054) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:122) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:459) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:121) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:55) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.DeleteStatement.executeInternal(DeleteStatement.kt:29) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.DeleteStatement.executeInternal(DeleteStatement.kt:20) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:92) ~[ledger-1.3.4.jar:?]
        ... 21 more
[14:48:44] [DefaultDispatcher-worker-8/警告]: Wait 34317 milliseconds before retrying

Purging actions older than 15 days
[14:49:19] [DefaultDispatcher-worker-12/警告]: Transaction attempt #1 failed: org.sqlite.SQLiteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed). Statement(s): DELETE FROM actions WHERE actions."time" <= ?
org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:94) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:244) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:221) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:55) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.DeleteStatement$Companion.where(DeleteStatement.kt:47) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.deleteWhere(Queries.kt:112) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.deleteWhere$default(Queries.kt:111) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$autoPurge$2.invokeSuspend(DatabaseManager.kt:133) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$autoPurge$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$autoPurge$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2.invokeSuspend(DatabaseManager.kt:384) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:187) [ledger-1.3.4.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [org_jetbrains_kotlin_kotlin-stdlib-2.0.0-e823d47a24b16be4.jar:?]
        at kotlinx.coroutines.Dispatched任务.run(DispatchedTask.kt:104) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.任务Impl.run(Tasks.kt:99) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.execute任务(CoroutineScheduler.kt:811) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
Caused by: org.sqlite.SQLiteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
        at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.DB.execute(DB.java:988) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.DB.executeUpdate(DB.java:1054) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:122) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:459) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:121) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:55) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.DeleteStatement.executeInternal(DeleteStatement.kt:29) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.DeleteStatement.executeInternal(DeleteStatement.kt:20) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:92) ~[ledger-1.3.4.jar:?]
        ... 21 more
[14:49:19] [DefaultDispatcher-worker-12/警告]: Wait 93854 milliseconds before retrying

### Steps/models to reproduce

1. Click on backup
2. Restore backup
3. The server cannot stop normally
4. Force stop and restore backup files
5. Error reported when opening the server
6. Error message when using Ledger

### What operating system are you running

Windows

### Minecraft version

1.21

### Ledger version

1.3.4

### Logs

.

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Natsusomekeishi** [comment]
[15:13:58] [信息]: 正在保存世界
[15:13:58] [信息]: 正在保存此维度的区块 'ServerLevel[world]'/minecraft:overworld
[15:13:59] [信息]: 正在保存此维度的区块 'ServerLevel[world]'/minecraft:the_nether
[15:13:59] [信息]: 正在保存此维度的区块 'ServerLevel[world]'/minecraft:the_end
[15:13:59] [信息]: ThreadedAnvilChunkStorage (world): 所有区块已被保存
[15:13:59] [信息]: ThreadedAnvilChunkStorage (DIM-1): 所有区块已被保存
[15:13:59] [信息]: ThreadedAnvilChunkStorage (DIM1): 所有区块已被保存
[15:13:59] [信息]: ThreadedAnvilChunkStorage: 所有维度已被保存
[15:13:59] [错误]: Exception stopping the server
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/container/mods/ledger-1.3.4.jar
        at net.fabricmc.loader.impl.util.LoaderUtil.normalizeExistingPath(LoaderUtil.java:46) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getCodeSource(KnotClassDelegate.java:515) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:363) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:338) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at com.github.quiltservertools.ledger.Ledger.serverStopped(Ledger.kt:116) ~[ledger-1.3.4.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$6(ServerLifecycleEvents.java:76) ~[fabric-lifecycle-events-v1-2.3.1+8f3583aed1-dbeb3a5728cf9ea6.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cep000$fabric-lifecycle-events-v1$afterShutdownServer(MinecraftServer.java:7652) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:637) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:561) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:735) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.nio.file.NoSuchFileException: /home/container/mods/ledger-1.3.4.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at java.base/sun.nio.fs.UnixPath.toRealPath(UnixPath.java:834) ~[?:?]
        at net.fabricmc.loader.impl.util.LoaderUtil.normalizeExistingPath(LoaderUtil.java:44) ~[fabric-loader-0.15.11.jar:?]
        ... 14 more
[15:14:12] [DefaultDispatcher-worker-4/警告]: Transaction attempt #1 failed: org.sqlite.SQLiteException: [SQLITE_错误] SQL error or missing database (no such table: players). Statement(s): SELECT players.id, players.player_id, players.player_name, players.first_join, players.last_join FROM players WHERE players.player_id = ?
org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_错误] SQL error or missing database (no such table: players)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:78) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:244) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:221) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.AbstractQuery.iterator(AbstractQuery.kt:78) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1.iterator(IterableEx.kt:160) ~[ledger-1.3.4.jar:?]
        at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:276) ~[org_jetbrains_kotlin_kotlin-stdlib-2.0.0-e823d47a24b16be4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager.insertOrUpdatePlayer(DatabaseManager.kt:436) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager.access$insertOrUpdatePlayer(DatabaseManager.kt:68) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$logPlayer$2.invokeSuspend(DatabaseManager.kt:359) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$logPlayer$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$logPlayer$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2.invokeSuspend(DatabaseManager.kt:384) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2.invoke(DatabaseManager.kt) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:187) [ledger-1.3.4.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [org_jetbrains_kotlin_kotlin-stdlib-2.0.0-e823d47a24b16be4.jar:?]
        at kotlinx.coroutines.Dispatched任务.run(DispatchedTask.kt:104) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.任务Impl.run(Tasks.kt:99) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.execute任务(CoroutineScheduler.kt:811) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
Caused by: org.sqlite.SQLiteException: [SQLITE_错误] SQL error or missing database (no such table: players)
        at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.DB.throwex(DB.java:1150) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:132) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.DB.prepare(DB.java:264) ~[ledger-1.3.4.jar:?]
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:225) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[ledger-1.3.4.jar:?]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:210) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.prepareStatement(JdbcConnectionImpl.kt:81) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:46) ~[ledger-1.3.4.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:74) ~[ledger-1.3.4.jar:?]
        ... 22 more
[15:14:12] [DefaultDispatcher-worker-4/警告]: Wait 87109 milliseconds before retrying

**Comment by Natsusomekeishi** [comment]
Can the mod ensure that the file data is not incorrect when forcibly shutting down the server?
