### ISSUE TITLE
The server is working fine but the mod have problems

### ISSUE THREAD

**Issue by zhizhizhiwang** [QuiltServerTools/Ledger#294]
### Expected behavior

The server runs without any strange errors

### Observed/actual behavior

Some repeated logs are like:
> INSERT OR IGNORE INTO ObjectIdentifiers (identifier) VALUES (?)

> [20:37:33] [DefaultDispatcher-worker-7/ERROR]: Uncaught exception in thread "DefaultDispatcher-worker-7"
org.jetbrains.exposed.exceptions.ExposedSQLException: java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:64) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:138) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:124) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.executeBatch(Queries.kt:179) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.batchInsert(Queries.kt:108) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.batchInsert(Queries.kt:94) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.batchInsert$default(Queries.kt:89) ~[ledger-1.2.8.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager.insertRegKeys(DatabaseManager.kt:376) ~[ledger-1.2.8.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager.access$insertRegKeys(DatabaseManager.kt:56) ~[ledger-1.2.8.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$insertIdentifiers$2.invokeSuspend(DatabaseManager.kt:336) ~[ledger-1.2.8.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$insertIdentifiers$2.invoke(DatabaseManager.kt) ~[ledger-1.2.8.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$insertIdentifiers$2.invoke(DatabaseManager.kt) ~[ledger-1.2.8.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2$1.invokeSuspend(DatabaseManager.kt:346) ~[ledger-1.2.8.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2$1.invoke(DatabaseManager.kt) ~[ledger-1.2.8.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$execute$2$1.invoke(DatabaseManager.kt) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:127) ~[ledger-1.2.8.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org_jetbrains_kotlin_kotlin-stdlib-2.0.21-6301f741d3f6049d.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException
Caused by: java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver
        at org.sqlite.jdbc3.JDBC3PreparedStatement.unsupported(JDBC3PreparedStatement.java:448) ~[grieflogger-1.1.5-fabric.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:361) ~[grieflogger-1.1.5-fabric.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.getResultSet(JdbcPreparedStatementImpl.kt:14) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:120) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:126) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12) ~[ledger-1.2.8.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:62) ~[ledger-1.2.8.jar:?]
        ... 24 more

### Steps/models to reproduce

>Linux master-node 5.4.0-190-generic #210-Ubuntu SMP Fri Jul 5 17:03:38 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

use fabric-server-mc.1.20.1-loader.0.16.5-launcher.1.0.1 with fabric-api-0.92.2+1.20.1
server run in java21 with sqlite-jdbc-3.47.0.0

run `lg status` and see :
>[20:35:33] [DefaultDispatcher-worker-6/INFO]: ------ Ledger ------
[20:35:33] [DefaultDispatcher-worker-6/INFO]: Database Queue: Empty
[20:35:33] [DefaultDispatcher-worker-6/INFO]: Version: 1.2.8
[20:35:33] [DefaultDispatcher-worker-6/INFO]: Database type: sqlite
[20:35:33] [DefaultDispatcher-worker-6/INFO]: Discord: Click to Join
[20:35:33] [DefaultDispatcher-worker-6/INFO]: Wiki: Click to View

I'm not a Java developer, and when I searched the web I saw a lot of methods about source code modification, but I couldn't apply them.
The database file is created correctly.

### What operating system are you running

Linux

### Minecraft version

1.20.1

### Ledger version

1.2.8

### Logs

https://mclo.gs/ZgKxU39

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

> My native language is Chinese, these contents are translated using Google Translate   

Please skip the part about mishanguc in the log (
1.2.8 is the latest version in 1.20.1, so I use the latest version of the mod ?

**Comment by baynarikattu** [comment]
Are you using GriefLogger and Ledger at the same time? What's the point of that??

**Comment by PotatoPresident** [comment]
Mod conflict
