### ISSUE TITLE
Negative index in crash report handler (0/21) / Error executing task on Server

### ISSUE THREAD

**Issue by zedwick** [QuiltServerTools/Ledger#47]
**Describe the bug**
Inspecting a chest with item transaction history yields an error in the logs.
The inspect otherwise appears successful, and shows the history in chat.

**To Reproduce**
1. Place a chest
2. Place any item into chest
3. /lg inspect
4. Left click on chest

**Expected behavior**
Everything seems to work, but I do not expect the error in the logs

**Device Info(please complete the following information):**
 - OS: Debian
 - Minecraft Version: 1.17
 - Version: 1.0.1

**Log**:
```
[20:20:31] [Server thread/INFO]: [STDOUT]: Negative index in crash report handler (0/21)
[20:20:31] [Server thread/FATAL]: Error executing task on Server
net.minecraft.class_148: Sending packet
        at net.minecraft.class_3244.method_14369(class_3244.java:1176) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_14364(class_3244.java:1164) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.handler$zbp001$startBlockBreak(class_3225.java:1038) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1029) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:783) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:765) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:759) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:744) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException
```

**Additional context**
The error does not show when left clicking an empty chest with no other history besides placing the chest.

**Comment by zedwick** [comment]
I disabled networking (`networking = false`) in the config, assuming it might be related to that, and restarted the server. I now see a slightly different/expanded error in the log when inspecting a chest with transaction history:

```
[20:37:44] [Server thread/FATAL]: Error executing task on Server
net.minecraft.class_148: Sending packet
        at net.minecraft.class_3244.method_14369(class_3244.java:1176) ~[intermediary-server.jar:?]                              
        at net.minecraft.class_3244.method_14364(class_3244.java:1164) ~[intermediary-server.jar:?]                              
        at net.minecraft.class_3225.handler$zbp001$startBlockBreak(class_3225.java:1038) ~[intermediary-server.jar:?]            
        at net.minecraft.class_3225.method_14263(class_3225.java) ~[intermediary-server.jar:?]                                   
        at net.minecraft.class_3244.method_12066(class_3244.java:1029) ~[intermediary-server.jar:?]                              
        at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[intermediary-server.jar:?]                                
        at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[intermediary-server.jar:?]                                 
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]                                
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]                                         
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]                               
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]                                
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:783) ~[intermediary-server.jar:?]              
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:167) ~[intermediary-server.jar:?]              
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]                               
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:765) ~[intermediary-server.jar:?]              
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:759) ~[intermediary-server.jar:?]              
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]                               
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:744) ~[intermediary-server.jar:?]              
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696) ~[intermediary-server.jar:?]              
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-server.jar:?]              
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "â˜ƒ" is null                               
        at net.minecraft.class_2539.method_10786(class_2539.java:486) ~[intermediary-server.jar:?]                               
        at net.minecraft.class_2535.method_10764(class_2535.java:185) ~[intermediary-server.jar:?]                               
        at net.minecraft.class_2535.method_10752(class_2535.java:178) ~[intermediary-server.jar:?]                               
        at net.minecraft.class_3244.method_14369(class_3244.java:1169) ~[intermediary-server.jar:?]                              
        ... 20 more
```

**Comment by yitzy299** [comment]
That’s the same error- and the networking code doesn’t fire on any in game action, unless a packet is sent to the server with the ledger ID

**Comment by zedwick** [comment]
Aye, it's just got a little more on the bottom and is missing the `Negative index in crash report handler (0/21)` line before it.

It may have just been the restart which changed the logged error slighty.

**Comment by yitzy299** [comment]
Would have been the same log anyway - the top one is a cut off one. Potato’s fixed it now

**Comment by PotatoPresident** [comment]
You can grab the fixed version from github actions

**Comment by zedwick** [comment]
Confirmed as fixed. Thank you.
