### ISSUE TITLE
Server crashes when I try to run with all the fabric 4

### ISSUE THREAD

**Issue by NebulaBC** [QuiltServerTools/Ledger#76]
### Expected behavior

Server should start up fine with ledger

### Observed/actual behavior

It threw the error log 
```
Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void org.jetbrains.exposed.sql.vendors.ColumnMetadata.<init>(java.lang.String, int, boolean, java.lang.Integer)'
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$columns$result$1.invoke(JdbcDatabaseMetadataImpl.java:135) ~[ledger-1.0.2.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$columns$result$1.invoke(JdbcDatabaseMetadataImpl.java:13) ~[ledger-1.0.2.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.extractColumns(JdbcDatabaseMetadataImpl.java:123) ~[ledger-1.0.2.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.columns(JdbcDatabaseMetadataImpl.java:133) ~[ledger-1.0.2.jar:?]
        at org.jetbrains.exposed.sql.vendors.VendorDialect$tableColumns$1.invoke(Default.kt:678) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.vendors.VendorDialect$tableColumns$1.invoke(Default.kt:678) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.java:51) ~[ledger-1.0.2.jar:?]
        at org.jetbrains.exposed.sql.vendors.VendorDialect.tableColumns(Default.kt:678) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.SchemaUtils.addMissingColumnsStatements(SchemaUtils.kt:117) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns(SchemaUtils.kt:247) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns$default(SchemaUtils.kt:235) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$ensureTables$1.invoke(DatabaseManager.java:77) ~[ledger-1.0.2.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager$ensureTables$1.invoke(DatabaseManager.java:76) ~[ledger-1.0.2.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:173) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:194) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:193) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:151) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:123) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:121) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:120) ~[d9e97d2b-3da9-493d-9678-f6d29630b45d.jar:?]
        at com.github.quiltservertools.ledger.database.DatabaseManager.ensureTables(DatabaseManager.java:76) ~[ledger-1.0.2.jar:?]
        at com.github.quiltservertools.ledger.Ledger.serverStarting(Ledger.java:71) ~[ledger-1.0.2.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:37) ~[c12f3ace-546b-4893-a264-d2665849c974.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cej000$beforeSetupServer(MinecraftServer.java:7802) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[14:58:24] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2021-08-24_14.58.24-server.txt
[14:58:24] [Server thread/INFO]: Stopping server
[14:58:24] [Server thread/INFO]: Saving worlds
[14:58:24] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "â˜ƒ" is null
        at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:588) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:624) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:585) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:734) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Steps/models to reproduce

1. Start up all the mods server
2. Add ledger
3. Start server

### What operating system are you running

Linux

### Minecraft version

1.17.1

### Ledger version

1.0.2

### Logs

https://neb.cx/dedavikuzo.sql

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Tom-The-Geek** [comment]
Unfortunately ledger is incompatible gunpowder at this point due to incompatibilities with the database library used by both mods. There are plans to switch to a different database system in the future which should fix this incompatibility.

**Comment by PotatoPresident** [comment]
Check EssentialCommands for most of the stuff gunpowder provides
